package net.minecraft.world.entity;

import java.util.HashMap;
import java.util.Map;

/**
 * How many synched-data accessors each entity class declares.
 *
 * <p><b>Generated by tools/gen_entity_data_counts.py - do not edit by hand.</b> The counts
 * are read out of decompiled-1.18.2-reference by counting SynchedEntityData.defineId call
 * sites per class literal, so they cannot drift from vanilla without the generator saying
 * so. Regenerate after changing anything that declares an accessor.
 *
 * <p>This exists to make {@code defineId} independent of class-initialisation order. Its
 * numbering walks up to the nearest ancestor that has <i>already initialised</i> and
 * continues from there, which assumes superclasses initialise before subclasses - a JVM
 * guarantee TeaVM does not make. When Sheep initialised before AgeableMob the walk stepped
 * over AgeableMob to Mob and numbered DATA_WOOL_ID 16 instead of 17; AgeableMob then took
 * 16 too, and every sheep in the world failed to spawn with "Duplicate id value for 16!".
 *
 * <p>With these counts the base id is arithmetic over the static hierarchy instead:
 * {@link #baseIdFor} sums the counts of every strict ancestor, which is the same number
 * vanilla arrives at and needs only {@code getSuperclass()}. Order stops mattering.
 *
 * <p>These ids travel on the wire, so they are not free to be merely self-consistent -
 * they have to be vanilla's, or entity metadata is misread by any real server this
 * connects to. tools/VerifyEntityDataIds.java checks them against a desktop JVM.
 */
public final class EntityDataAccessorCounts {

	private static final Map<Class<?>, Integer> COUNTS = new HashMap<>(158);

	static {
		COUNTS.put(net.minecraft.world.entity.AgeableMob.class, 1);
		COUNTS.put(net.minecraft.world.entity.AreaEffectCloud.class, 4);
		COUNTS.put(net.minecraft.world.entity.Entity.class, 8);
		COUNTS.put(net.minecraft.world.entity.GlowSquid.class, 1);
		COUNTS.put(net.minecraft.world.entity.LivingEntity.class, 7);
		COUNTS.put(net.minecraft.world.entity.Mob.class, 1);
		COUNTS.put(net.minecraft.world.entity.TamableAnimal.class, 2);
		COUNTS.put(net.minecraft.world.entity.ambient.Bat.class, 1);
		COUNTS.put(net.minecraft.world.entity.animal.AbstractFish.class, 1);
		COUNTS.put(net.minecraft.world.entity.animal.Bee.class, 2);
		COUNTS.put(net.minecraft.world.entity.animal.Cat.class, 4);
		COUNTS.put(net.minecraft.world.entity.animal.Dolphin.class, 3);
		COUNTS.put(net.minecraft.world.entity.animal.Fox.class, 4);
		COUNTS.put(net.minecraft.world.entity.animal.IronGolem.class, 1);
		COUNTS.put(net.minecraft.world.entity.animal.MushroomCow.class, 1);
		COUNTS.put(net.minecraft.world.entity.animal.Ocelot.class, 1);
		COUNTS.put(net.minecraft.world.entity.animal.Panda.class, 6);
		COUNTS.put(net.minecraft.world.entity.animal.Parrot.class, 1);
		COUNTS.put(net.minecraft.world.entity.animal.Pig.class, 2);
		COUNTS.put(net.minecraft.world.entity.animal.PolarBear.class, 1);
		COUNTS.put(net.minecraft.world.entity.animal.Pufferfish.class, 1);
		COUNTS.put(net.minecraft.world.entity.animal.Rabbit.class, 1);
		COUNTS.put(net.minecraft.world.entity.animal.Sheep.class, 1);
		COUNTS.put(net.minecraft.world.entity.animal.SnowGolem.class, 1);
		COUNTS.put(net.minecraft.world.entity.animal.TropicalFish.class, 1);
		COUNTS.put(net.minecraft.world.entity.animal.Turtle.class, 6);
		COUNTS.put(net.minecraft.world.entity.animal.Wolf.class, 3);
		COUNTS.put(net.minecraft.world.entity.animal.axolotl.Axolotl.class, 3);
		COUNTS.put(net.minecraft.world.entity.animal.goat.Goat.class, 1);
		COUNTS.put(net.minecraft.world.entity.animal.horse.AbstractChestedHorse.class, 1);
		COUNTS.put(net.minecraft.world.entity.animal.horse.AbstractHorse.class, 2);
		COUNTS.put(net.minecraft.world.entity.animal.horse.Horse.class, 1);
		COUNTS.put(net.minecraft.world.entity.animal.horse.Llama.class, 3);
		COUNTS.put(net.minecraft.world.entity.boss.enderdragon.EndCrystal.class, 2);
		COUNTS.put(net.minecraft.world.entity.boss.enderdragon.EnderDragon.class, 1);
		COUNTS.put(net.minecraft.world.entity.boss.wither.WitherBoss.class, 4);
		COUNTS.put(net.minecraft.world.entity.decoration.ArmorStand.class, 7);
		COUNTS.put(net.minecraft.world.entity.decoration.ItemFrame.class, 2);
		COUNTS.put(net.minecraft.world.entity.item.FallingBlockEntity.class, 1);
		COUNTS.put(net.minecraft.world.entity.item.ItemEntity.class, 1);
		COUNTS.put(net.minecraft.world.entity.item.PrimedTnt.class, 1);
		COUNTS.put(net.minecraft.world.entity.monster.Blaze.class, 1);
		COUNTS.put(net.minecraft.world.entity.monster.Creeper.class, 3);
		COUNTS.put(net.minecraft.world.entity.monster.EnderMan.class, 3);
		COUNTS.put(net.minecraft.world.entity.monster.Ghast.class, 1);
		COUNTS.put(net.minecraft.world.entity.monster.Guardian.class, 2);
		COUNTS.put(net.minecraft.world.entity.monster.Phantom.class, 1);
		COUNTS.put(net.minecraft.world.entity.monster.Pillager.class, 1);
		COUNTS.put(net.minecraft.world.entity.monster.Shulker.class, 3);
		COUNTS.put(net.minecraft.world.entity.monster.Skeleton.class, 1);
		COUNTS.put(net.minecraft.world.entity.monster.Slime.class, 1);
		COUNTS.put(net.minecraft.world.entity.monster.SpellcasterIllager.class, 1);
		COUNTS.put(net.minecraft.world.entity.monster.Spider.class, 1);
		COUNTS.put(net.minecraft.world.entity.monster.Strider.class, 3);
		COUNTS.put(net.minecraft.world.entity.monster.Vex.class, 1);
		COUNTS.put(net.minecraft.world.entity.monster.Witch.class, 1);
		COUNTS.put(net.minecraft.world.entity.monster.Zoglin.class, 1);
		COUNTS.put(net.minecraft.world.entity.monster.Zombie.class, 3);
		COUNTS.put(net.minecraft.world.entity.monster.ZombieVillager.class, 2);
		COUNTS.put(net.minecraft.world.entity.monster.hoglin.Hoglin.class, 1);
		COUNTS.put(net.minecraft.world.entity.monster.piglin.AbstractPiglin.class, 1);
		COUNTS.put(net.minecraft.world.entity.monster.piglin.Piglin.class, 3);
		COUNTS.put(net.minecraft.world.entity.npc.AbstractVillager.class, 1);
		COUNTS.put(net.minecraft.world.entity.npc.Villager.class, 1);
		COUNTS.put(net.minecraft.world.entity.player.Player.class, 6);
		COUNTS.put(net.minecraft.world.entity.projectile.AbstractArrow.class, 2);
		COUNTS.put(net.minecraft.world.entity.projectile.Arrow.class, 1);
		COUNTS.put(net.minecraft.world.entity.projectile.EyeOfEnder.class, 1);
		COUNTS.put(net.minecraft.world.entity.projectile.Fireball.class, 1);
		COUNTS.put(net.minecraft.world.entity.projectile.FireworkRocketEntity.class, 3);
		COUNTS.put(net.minecraft.world.entity.projectile.FishingHook.class, 2);
		COUNTS.put(net.minecraft.world.entity.projectile.ThrowableItemProjectile.class, 1);
		COUNTS.put(net.minecraft.world.entity.projectile.ThrownTrident.class, 2);
		COUNTS.put(net.minecraft.world.entity.projectile.WitherSkull.class, 1);
		COUNTS.put(net.minecraft.world.entity.raid.Raider.class, 1);
		COUNTS.put(net.minecraft.world.entity.vehicle.AbstractMinecart.class, 6);
		COUNTS.put(net.minecraft.world.entity.vehicle.Boat.class, 7);
		COUNTS.put(net.minecraft.world.entity.vehicle.MinecartCommandBlock.class, 2);
		COUNTS.put(net.minecraft.world.entity.vehicle.MinecartFurnace.class, 1);
	}

	/**
	 * The first id belonging to {@code type}: the number of accessors declared by all of
	 * its ancestors together.
	 *
	 * <p>Classes that declare none are simply absent from the table and contribute zero,
	 * which is also how vanilla treats them - they never enter its pool, so its walk passes
	 * straight through them.
	 */
	public static int baseIdFor(Class<?> type) {
		int base = 0;
		for (Class<?> c = type.getSuperclass(); c != null; c = c.getSuperclass()) {
			Integer declared = COUNTS.get(c);
			if (declared != null) {
				base += declared.intValue();
			}
			if (c == Entity.class) {
				break;
			}
		}
		return base;
	}

	/** How many accessors {@code type} itself declares; 0 if it declares none. */
	public static int declaredBy(Class<?> type) {
		Integer declared = COUNTS.get(type);
		return declared == null ? 0 : declared.intValue();
	}

	private EntityDataAccessorCounts() {
	}
}
