/**
 * Checks the ISO3_COUNTRIES table embedded in
 * src/nio-shim/java/org/teavm/classlib/java/util/TLocale.java against this machine's JDK.
 *
 *     java tools/CheckIso3Table.java
 *
 * The table is the data behind Locale.getISO3Country(), which TeaVM's class library does not
 * implement and Minecraft's PeriodicNotificationManager calls during the first resource
 * reload. It was generated by asking the JDK for every code in Locale.getISOCountries(), so
 * this re-asks and compares: every record must round-trip, no duplicates, and no country the
 * JDK knows may be absent. It exists because the table was assembled by string concatenation
 * across source lines, where an off-by-one at a line boundary would shift every record after
 * it and still look like a plausible table.
 */
import java.util.*;
import java.nio.file.*;
import java.util.regex.*;
public class CheckIso3Table {
    public static void main(String[] a) throws Exception {
        String src = Files.readString(Path.of(
            "src/nio-shim/java/org/teavm/classlib/java/util/TLocale.java"));
        String blk = src.split("ISO3_COUNTRIES = \"\"", 2)[1].split(";", 2)[0];
        StringBuilder t = new StringBuilder();
        Matcher m = Pattern.compile("\"([^\"]*)\"").matcher(blk);
        while (m.find()) t.append(m.group(1));
        String table = t.toString();
        if (table.length() % 5 != 0) throw new AssertionError("table length " + table.length());
        // every record must round-trip against the JDK
        Set<String> seen = new HashSet<>();
        for (int i = 0; i < table.length(); i += 5) {
            String two = table.substring(i, i + 2), three = table.substring(i + 2, i + 5);
            if (!seen.add(two)) throw new AssertionError("duplicate " + two);
            String jdk = new Locale("", two).getISO3Country();
            if (!jdk.equals(three)) throw new AssertionError(two + " -> " + three + " but JDK says " + jdk);
        }
        // and every country the JDK knows must be in the table
        int missing = 0;
        for (String c : Locale.getISOCountries()) {
            String jdk;
            try { jdk = new Locale("", c).getISO3Country(); } catch (MissingResourceException e) { continue; }
            if (jdk.length() != 3) continue;
            if (!seen.contains(c)) { System.out.println("MISSING " + c + " " + jdk); ++missing; }
        }
        if (missing > 0) throw new AssertionError(missing + " countries missing from the table");
        System.out.println("OK - " + seen.size() + " records, all agree with the JDK, none missing");
    }
}
