"""Generate EntityDataAccessorCounts.java: how many synched-data accessors each class declares.

Why this exists: SynchedEntityData.defineId numbers a class's accessors by finding its nearest
*already initialised* ancestor in a pool and continuing from there. That is correct only if a
superclass's static initialiser always runs before a subclass's, which is a JVM guarantee that
TeaVM does not make. When it does not hold the walk skips the uninitialised ancestor and
numbers the subclass over the top of it - Sheep was numbered from 16 because AgeableMob had not
initialised yet, and AgeableMob then claimed 16 as well.

Counting the accessors per class turns the base id into arithmetic over the *static* class
hierarchy: base(X) = sum of counts of every strict ancestor of X. That is the same number
vanilla arrives at, and it needs only getSuperclass(), so initialisation order stops mattering.

The counts come from the decompiled reference rather than from a hand-written list, so adding
or removing an accessor upstream cannot silently desync them.

    python tools/gen_entity_data_counts.py

Verify the result with tools/VerifyEntityDataIds.java, which checks the ids this produces
against the real ones on a desktop JVM.
"""

import io
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
REFERENCE = os.path.join(ROOT, 'decompiled-1.18.2-reference')
OUT = os.path.join(ROOT, 'src', 'game', 'java', 'net', 'minecraft', 'world', 'entity',
                   'EntityDataAccessorCounts.java')

DEFINE_ID = re.compile(r'SynchedEntityData\.defineId\(\s*([A-Za-z_][A-Za-z0-9_]*)\.class')
PACKAGE = re.compile(r'^package\s+([A-Za-z0-9_.]+)\s*;', re.M)


def main():
    if not os.path.isdir(REFERENCE):
        print('reference tree not found: ' + REFERENCE, file=sys.stderr)
        return 1

    counts = {}          # simple name -> number of accessors declared
    fqn = {}             # simple name -> fully qualified name

    for dirpath, _, files in os.walk(REFERENCE):
        for name in files:
            if not name.endswith('.java'):
                continue
            path = os.path.join(dirpath, name)
            text = io.open(path, encoding='utf-8', errors='replace').read()

            # Record this file's own class, so a class literal can be resolved to an FQN.
            m = PACKAGE.search(text)
            if m:
                fqn.setdefault(name[:-len('.java')], m.group(1) + '.' + name[:-len('.java')])

            for found in DEFINE_ID.finditer(text):
                simple = found.group(1)
                counts[simple] = counts.get(simple, 0) + 1

    missing = sorted(c for c in counts if c not in fqn)
    if missing:
        print('could not resolve a package for: ' + ', '.join(missing), file=sys.stderr)
        return 1

    rows = sorted(counts.items(), key=lambda kv: fqn[kv[0]])
    total = sum(counts.values())

    lines = []
    add = lines.append
    add('package net.minecraft.world.entity;')
    add('')
    add('import java.util.HashMap;')
    add('import java.util.Map;')
    add('')
    add('/**')
    add(' * How many synched-data accessors each entity class declares.')
    add(' *')
    add(' * <p><b>Generated by tools/gen_entity_data_counts.py - do not edit by hand.</b> The counts')
    add(' * are read out of decompiled-1.18.2-reference by counting SynchedEntityData.defineId call')
    add(' * sites per class literal, so they cannot drift from vanilla without the generator saying')
    add(' * so. Regenerate after changing anything that declares an accessor.')
    add(' *')
    add(' * <p>This exists to make {@code defineId} independent of class-initialisation order. Its')
    add(' * numbering walks up to the nearest ancestor that has <i>already initialised</i> and')
    add(' * continues from there, which assumes superclasses initialise before subclasses - a JVM')
    add(' * guarantee TeaVM does not make. When Sheep initialised before AgeableMob the walk stepped')
    add(' * over AgeableMob to Mob and numbered DATA_WOOL_ID 16 instead of 17; AgeableMob then took')
    add(' * 16 too, and every sheep in the world failed to spawn with "Duplicate id value for 16!".')
    add(' *')
    add(' * <p>With these counts the base id is arithmetic over the static hierarchy instead:')
    add(' * {@link #baseIdFor} sums the counts of every strict ancestor, which is the same number')
    add(' * vanilla arrives at and needs only {@code getSuperclass()}. Order stops mattering.')
    add(' *')
    add(' * <p>These ids travel on the wire, so they are not free to be merely self-consistent -')
    add(' * they have to be vanilla\'s, or entity metadata is misread by any real server this')
    add(' * connects to. tools/VerifyEntityDataIds.java checks them against a desktop JVM.')
    add(' */')
    add('public final class EntityDataAccessorCounts {')
    add('')
    add('\tprivate static final Map<Class<?>, Integer> COUNTS = new HashMap<>(%d);' % (len(rows) * 2))
    add('')
    add('\tstatic {')
    for simple, n in rows:
        add('\t\tCOUNTS.put(%s.class, %d);' % (fqn[simple], n))
    add('\t}')
    add('')
    add('\t/**')
    add('\t * The first id belonging to {@code type}: the number of accessors declared by all of')
    add('\t * its ancestors together.')
    add('\t *')
    add('\t * <p>Classes that declare none are simply absent from the table and contribute zero,')
    add('\t * which is also how vanilla treats them - they never enter its pool, so its walk passes')
    add('\t * straight through them.')
    add('\t */')
    add('\tpublic static int baseIdFor(Class<?> type) {')
    add('\t\tint base = 0;')
    add('\t\tfor (Class<?> c = type.getSuperclass(); c != null; c = c.getSuperclass()) {')
    add('\t\t\tInteger declared = COUNTS.get(c);')
    add('\t\t\tif (declared != null) {')
    add('\t\t\t\tbase += declared.intValue();')
    add('\t\t\t}')
    add('\t\t\tif (c == Entity.class) {')
    add('\t\t\t\tbreak;')
    add('\t\t\t}')
    add('\t\t}')
    add('\t\treturn base;')
    add('\t}')
    add('')
    add('\t/** How many accessors {@code type} itself declares; 0 if it declares none. */')
    add('\tpublic static int declaredBy(Class<?> type) {')
    add('\t\tInteger declared = COUNTS.get(type);')
    add('\t\treturn declared == null ? 0 : declared.intValue();')
    add('\t}')
    add('')
    add('\tprivate EntityDataAccessorCounts() {')
    add('\t}')
    add('}')

    io.open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
    print('wrote %s' % OUT)
    print('%d classes, %d accessors total' % (len(rows), total))
    return 0


if __name__ == '__main__':
    sys.exit(main())
